### ISSUE TITLE
Allow text/plain json bodies

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#113]
According to test_storage::test_set_item_input_formats this is a bw-compat case we need to support:

```python
        # Unless we use text/plain, which is a special bw-compat case.
        self.app.put(self.root + '/storage/col2/TEST', body, headers={
            "Content-Type": "text/plain"
        })
```

**Comment by philbooth** [comment]
@pjenvey I don't see `test_set_item_input_formats` in the server-syncstorage repo. Am I missing something?

**Comment by philbooth** [comment]
> Am I missing something?

Only my own foolishness it seems. Forgot that I deleted a load of tests in my local copy, sorry, ignore the above.

**Comment by philbooth** [comment]
This is because of the implementation of [`actix_web::dev::JsonBody`](https://actix.rs/api/actix-web/stable/actix_web/dev/struct.JsonBody.html), which fails if content type is not `application/json`.

`JsonBody::from_request` is called internally when we do the following in `BsoBody::from_request`:

```rust
let fut = <Json<BsoBody>>::from_request(req, &config)
```

The docs mention [`actix_web::dev::JsonConfig`](https://actix.rs/api/actix-web/stable/actix_web/dev/struct.JsonConfig.html) as a way to configure the built-in JSON extraction, but you can't disable the header check that way. So it looks like we'll need to deserialize the payload ourselves instead, I'll aim to wrap that up in something that looks the same as the actix's `Json`.

**Comment by philbooth** [comment]
Fwiw, I've opened a PR to see if we can fix this on the actix side: actix/actix-web#637

**Comment by jrconlin** [comment]
Looks like this was merged in https://github.com/actix/actix-web/pull/637.

Is this still a relevant bug? Should we open a new one to remove our hack and apply a "proper" fix using the actix lib?

**Comment by pjenvey** [comment]
> Is this still a relevant bug? Should we open a new one to remove our hack and apply a "proper" fix using the actix lib?

Yep, this is still an issue (we don't have a hack for it, test_set_item_input_formats still fails in the same spot).

The fix required is to begin utilizing the JsonConfig::content_type method that pb added to actix-web. The example in that PR's docs/tests appear to be exactly what we need (allowing `mime.type_() == mime::TEXT && mime.subtype() == mime::PLAIN`
