### ISSUE TITLE
DB Lock Failures not being properly reported

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#146]
The `middleware::DbTransaction` is not reporting when a database lock failure occurs. This cascades to cause a 500 error when there's no request extension for web/extractors `FromRequest<ServerState> for Box<dyn Db>::from_request()` fails with a generic "Unexpected Db[sic] error".

The 500 response is technically correct, but the reason can be easily lost.

**Comment by pjenvey** [comment]
This is another middleware related issue,

- The `DbTransaction` middleware may trigger ConflictErrors on lock_for_write, by design
- `DbTransaction::start` erroring out appears to prevent `PreconditionCheck::start` from running, but `PreconditionCheck::response` still runs.. (not what I would have expected)
- Regardless, PreconditionCheck start or response (actually the Box<dyn Db> extractor) always assumes it has a Db available, erroring out with an ErrorInternalServerError("Unexpected DB error") if not

So ultimately the ErrorInternalServerError propagates out as a 500. We'll fix this when updating the middleware to actix 1.0

**Comment by tublitzed** [comment]
@jrconlin is this one still in progress?

**Comment by jrconlin** [comment]
@tublitzed Nope.

Closed with https://github.com/mozilla-services/syncstorage-rs/pull/185
