### ISSUE TITLE
Audit the Schema

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#194]
- STRING for payloads? We may need to continue using STRING for compatibility with the Python version, but if we were able to use BYTES instead we could save storage and bandwidth
- Secondary indices: we may requirement multiple indicies depending on the order specified on get_bsos

**Comment by jrconlin** [comment]
Looking at the protobuf docs, I think we kinda/sorta are stuck with strings. Mostly because looking at the protobuf [value declarations](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#bytesvalue), and the [protobuf protocol](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec#string_literals), I think that "bytes" basically maps to an encoded string).

**Comment by jrconlin** [comment]
We need to make sure that the spanner schema matches the mysql one so that self hosting remains possible.
