### ISSUE TITLE
Add a deleted_at to user_collections table

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#23]
See rfk's comments here:

https://github.com/mozilla-services/syncstorage-rs/pull/22#discussion_r216541111

I believe the go version gets away without this field because it stores the top level modified timestamp separately in its per user KeyValues store.
https://github.com/mozilla-services/server-syncstorage/pull/62

**Comment by jrconlin** [comment]
From what I've been [able to see](https://github.com/mozilla-services/go-syncstorage/issues/169), the bug is that on a collections deletion:
1) the collection X-Last-Modified should be set to 0 
2) the collection dropped from the /info/collections
3) Maintain the last time that the store was modified. 

#3 seems like the trickier bit, and probably requires a "meta data" table.
