### ISSUE TITLE
Sync not working in iOS

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#277]
Sync is partially working in iOS (as of [recent fix](https://github.com/mozilla-mobile/firefox-ios/pull/5620) merged to firefox-ios v20.0)

Testing has been performed against staging and production so far. We're seeing the same problem in both places.

What's working:

* History

What's broken:

* Bookmarks

What's not yet been tested:

* Logins
* Addresses
* Preferences
* Add-ons (do these even work in iOS?)

To repro, first [follow these instructions](https://docs.google.com/document/d/1KnFdE1ee-yv8En5QaPoRj3x2s9kTESoW0lGNh2LwIrI/edit) to point iOS at durable sync in staging, or just get your sync id routed to spanner in production.

**Comment by tublitzed** [comment]
Some tips for testing sync in iOS: 

`build firefox-ios and sideload it through xcode so you can get logs`

**Comment by fzzzy** [comment]
Opened a pull request against firefox ios: https://github.com/mozilla-mobile/firefox-ios/pull/5620

This fixes the crash, but sync still doesn't seem to complete properly.

**Comment by tublitzed** [comment]
Thanks, @fzzzy! Let's just keep this one open to address whatever else is going on then with Sync not working properly after that one gets in.

**Comment by fzzzy** [comment]
It's merged already. I'll keep an eye open to see when the next Firefox iOS release is, then test again.

**Comment by fzzzy** [comment]
Since old iOS versions will still crash, we're going to investigate having the server notice if an old iOS client logs in (using the user agent header), and have the server respond in a way that prevents it from syncing until the version is updated to a version that won't crash.

This will break sync on iOS for everyone that hasn't updated, but at least they won't instantly crash.

We could also explore whether there is a way to push a notification to anyone that tries to sync with an old, crashy ios version, to let them know they won't be able to sync until they upgrade.

We're probably going to have to have product make some decisions here about what acceptable breakage looks like.

**Comment by fzzzy** [comment]
There was something wrong with the way we were testing against stage. Once we had a production spanner instance set up and we were able to test with the release version of firefox ios, we found that things were working as expected.

There are still two separate issues:

  - firefox ios does not pass a custom tokenserver url through to rust-components
  - old versions of firefox ios will still crash if they try to log in to a spanner server

but we'll file another bug for the first one, and the second one isn't critical right now because we will initially only be rolling spanner out to new users, who aren't likely to have an old, unupdated firefox ios.
