### ISSUE TITLE
Allow configurable debug mode via env var

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#334]
To help with diagnosing issues in the logs. Ie, https://github.com/mozilla-services/syncstorage-rs/blob/master/src/settings.rs#L51

First, let's just do a quick test and make sure we actually get any more useful log output with this set to true. Assuming yes, let's swap that out with an env var.

**Comment by jrconlin** [comment]
I'm wondering if this might be a good reason to enable https://github.com/tokio-rs/tracing. (which might require a bit more effort, but would give a lot more control over log output)

**Comment by pjenvey** [comment]
`Settings'` values are all configurable via env var (thanks to the config crate), so you can already set `SYNC_DEBUG=true`. However debug isn't wired to actually do anything yet, I think it just got copied from autopush/autopush-rs.

Since we can already fine tune logging configuration via `SYNC_HUMAN_LOGS` and `RUST_LOG` env vars, I'm fine with nuking debug entirely. Or we can come up with some sane debugging settings for it to enable.

**Comment by tublitzed** [comment]
@pjenvey - yeah, I think if it's not wired up to do anything, then probably just makes sense to remove entirely. Also; if I'm reading this right, [human_logs](https://github.com/mozilla-services/syncstorage-rs/blob/master/src/settings.rs#L77) here doesn't actually read anything from `SYNC_HUMAN_LOGS` env var, does it?

Also, what do you think about using something like [dotenv](https://docs.rs/dotenv/0.15.0/dotenv/) to make it easier to load env vars locally for testing? I like that pattern too as it gives us a clear place (ie, `.env.example`) to keep sample placeholder values for what we're using as env vars so we don't have to go poking through code later to see what's actually being read.

**Comment by jrconlin** [comment]
There's a bit of magic that `Config::default().merge(Environment::with_prefix(PREFIX))` does. It goes through the environment and polls anything starting with `PREFIX`, so `SYNC_HUMAN_LOGS` sets `human_logs`. 

The priorities are:
config file (only used if `--config=<FILENAME>`)
which is overriden by what ever is in `env`
which is overriden by what ever is specified as an argument. 

We probably want to stick with `env` when ever possible,since that's easiest for the ops folk to deal with.  Recently, I created a semi-hack to add a config file, mostly because I was having problems specifying one of the options, which I believe @pjenvey found a potential solution for, but I've not tested it yet.

We could probably use a default config file of something like `.syncstorage.ini` or something. We do that for autopush already. but it's lead to some end user confusion.

**Comment by tublitzed** [comment]
@jrconlin I completely agree with sticking with ENV when possible for stg/prod/etc. I'm suggesting that we use something like `dotenv` for helping locally only. Ie: `.env` goes into `.gitignore` so it never gets checked in. Then `.env.example` gets checked in with example values. Helps make the codebase a bit more readable (IMO, feel free to disagree here) as the ENV vars used aren't scattered around all over the place, they're in one list.

Then, instead of having to include instructions to `cargo run` with a bunch of prefixed env vars, users can just `cargo run` and keep their env vars in a separate local file. 

Not a huge deal (or related to this specific issue actually), but on the subject of env vars, it might be nice to have.

**Comment by tublitzed** [comment]
Just found details on using the `config` crate with the file param. I _think_ that's plenty here. Gonna just close this out and plan on adding an example to the repo that's gitignore-d.

**Comment by tublitzed** [comment]
For complete-ness sake here, passing `RUST_LOG=debug` through as an env var is already wired and accomplishes this.
