### ISSUE TITLE
Prevent complete client re-upload during migration.

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#568]
It looks like, from [testing done here](https://github.com/mozilla-services/services-engineering/issues/45) that we are re-uploading all collections in full for the first sync a user goes through post-migration.

**Comment by tublitzed** [comment]
We will also need to verify that users on a fresh install can get at their migrated data with our approach here. It looks like, as of [testing here](https://github.com/mozilla-services/services-engineering/issues/46) that's not currently working as expected.

**Comment by pjenvey** [comment]
> It looks like, from [testing done here](https://github.com/mozilla-services/services-engineering/issues/45) that we are re-uploading all collections in full for the first sync a user goes through post-migration.

This was fixed by a couple issues:

-  #561, namely 84e1efb which fixed the broken `--user` argument used for migrating individual users (for this test)
-  `migrate_node.py` wasn't running with the correct arguments when migrating individual users. The `--deanon` argument wasn't being specified (so migrated data was anonymized & thus not found by the client). this argument was more for testing and is now no longer required

**Comment by erkolson** [comment]
For individual user migrations, I don't think the second point is true.  The `--user` flag was used and `--deanon` was not.

Have we done a user migration test after #561 was fixed?

**Comment by pjenvey** [comment]
> Have we done a user migration test after #561 was fixed?

Not officially but I've confirmed the fix on a migration I did locally

**Comment by erkolson** [comment]
Great!  Lets migrate a few users over to test in prod.
