### ISSUE TITLE
unable to complete purge_ttl run

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#631]
See bugzilla issue here: [1626707](https://bugzilla.mozilla.org/show_bug.cgi?id=1626707).

Going to keep this one open until we feel confident we can run purge_ttl at the scale needed in order to complete the migrated.

**Comment by erkolson** [comment]
Updates here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1626707#c9

tl;dr, We are purging rows effectively now and will probably be down to zero each night tonight.

Deleted rows can take up to 48 hours to be deleted off disk and the 30-day trend of spanner disk usage shows a flatline for several days as purged rows are being removed permanently
<img width="1648" alt="Screen Shot 2020-05-18 at 1 40 17 PM" src="https://user-images.githubusercontent.com/9535472/82243516-c65f9980-990d-11ea-90f0-b0f25eba8da8.png">

**Comment by pjenvey** [comment]
The 60 minute limit we're stopping at may be related to a one of the timeout values set in the driver (36000000):

https://github.com/googleapis/python-spanner/blob/62edbe1/google/cloud/spanner_v1/gapic/spanner_client_config.py#L28

I wonder if we're able to overwrite these values with larger values.

**Comment by pjenvey** [comment]
According to the client team ([May 18th Sync Teams Sync](https://docs.google.com/document/d/1AlYkT4CaQiT3nnTnVqVMq3LbAu293EufiVgz53VqmLY/edit#)) only 4 collections utilize TTLs: History (2 months), clients (3 weeks), forms (3 years), tabs (1 year).

We can sort of confirm this, running against stage:

```
SELECT bsos.collection_id, collections.name, COUNT(bsos.expiry)
  FROM bsos
  LEFT JOIN collections
    ON bsos.collection_id = collections.collection_id
 WHERE expiry < CURRENT_TIMESTAMP()
 GROUP BY bsos.collection_id, collections.name
 ORDER BY bsos.collection_id
```

collection_id | name | Unspecified
--- | --- | ---
1 | clients | 543
3 | forms | 724250
4 | history | 757858
7 | bookmarks | 749967
8 | prefs | 730457
9 | tabs | 35
10 | passwords | 731108


The 5 collections with the large numbers are due to the load tester: https://github.com/mozilla-services/syncstorage-loadtest/blob/535dd4b/loadtest.py#L24

Could narrowing the number of collection_ids to the 4 (clients/forms/history/tabs) help purge_ttl's PDML? We're already hitting the `BsoExpiry` index so it may not due much, however `BsoExpiry` is interleaved in `user_collections` so it's possible the restriction would reduce its workload. If we do this we would probably want to purge all the other collections (or maybe non standard collections w/ collection_id >= 100) just in case there's non-standard usages of ttl there but this could be a much less frequent operation.

**Comment by erkolson** [comment]
Production from this morning:

collection_id | name | Unspecified
-- | -- | --
1 | clients | 31614
2 | crypto | 412
3 | forms | 1594
4 | history | 68515668
6 | meta | 403
9 | tabs | 10512

Curious to see if we get faster progress by just focusing on history, there could be a lot of cycles scanning through all the other collections.

**Comment by pjenvey** [comment]
> Production from this morning:

How long did this take to run?

**Comment by erkolson** [comment]
About 500s, just ran it again and it was 473s

**Comment by tublitzed** [comment]
Going to close this one and open new specific issues for targeted changes.
