### ISSUE TITLE
Move from_request for BatchRequestOpt into a normal function.

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/syncstorage-rs#710]
Currently, post_collection and post_collection_batch use the CollectionPostRequest extractor, which uses the BatchRequestOpt extractor, which requires a database connection. This is less than optimal.

post_collection and post_collection_batch should get the information from a function to which they pass the database handle running the current transaction, instead.

The BatchRequestOpt extractor should be deleted, and CollectionPostRequest modified to no longer contain the field with the BatchRequestOpt type.

**Comment by ethowitz** [comment]
I've started digging into this issue, and it looks like it may not be needed anymore. @pjenvey commented [here](https://github.com/mozilla-services/syncstorage-rs/pull/692#discussion_r452549901) that in order to avoid a second database transaction, we should add `validate_batch_id` to `DbPool` instead of `Db`, and it looks like that change was made in that PR. Looking at `BatchRequestOpt` as it exists today, I see that we do in fact [get the transaction pool](https://github.com/mozilla-services/syncstorage-rs/blob/master/src/web/extractors.rs#L1408), but we don't seem to create a new transaction, so I don't _think_ we actually acquire a second database connection.

That said, we could still probably remove the `BatchRequestOpt` extractor and instead rely on a function defined on `CollectionPostRequest`, but I'm not sure whether that's preferable to how things are currently organized.
