### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by citydelver** [mozilla-services/syncstorage-rs#825]
Hello. I would like to know what are the security and privacy measures in place for synced/backed-up user data, and specially if there's a zero knowledge policy in place, please.

**Comment by fzzzy** [comment]
https://hacks.mozilla.org/2018/11/firefox-sync-privacy/

**Comment by martin-braun** [comment]
@fzzzy Thanks, this explains very well how the data is encrypted. Asymmetric encryption is great and secure for data security, but what about hardware-theft?

It's unclear to me how and if the data is encrypted in the database itself. The [syncserver.ini](https://github.com/mozilla-services/syncserver/blob/master/syncserver.ini) contains the master key, but this is a huge flaw in my opinion. If someone gets access to the server, he can get all data, he can not?

In my opinion all data should be encrypted in the database and private key (the passphrase) should be used on the client to decrypt the data. 

Is there an additional passphrase to ensure the data is protected against data leakage / hardware theft? Please tell me I am missing something here?

**Comment by jrconlin** [comment]
I think you might have misunderstood how sync works, but that's fair, it's a bit opaque. In addition, the encryption elements are [part of Firefox Accounts](https://github.com/mozilla/fxa-auth-server/wiki/onepw-protocol), so it can be hard to find the association. (Please note, while that repo's source has been archived in favor of the new [fxa-auth-server](https://github.com/mozilla/fxa/tree/main/packages/fxa-auth-server), the documents are still correct. 

The sync storage server doesn't do any additional encryption because, by that point, the data is already encrypted. User data is encrypted on the client using a set of keys that are derived from the user ID and the password. This is why when you change or lose your sync password, all of your previously synced data is no longer accessible. The "Authentication token" noted is there to ensure that only your account has access to the encrypted data stores. It does not provide any of the decryption key data. 

Each set of data (passwords, history, bookmarks, etc.) are stored as "collections" and are client side encrypted. There is one collection (meta) that is not, but this collection contains only larger meta data about the collections being stored. 

Encrypting the data further on the server could be done, but would be fairly redundant. Plus, there would be the risk that we might be able to read your data and that would not be good at all.

Of course, it's always possible to set up your own instance of the sync server and verify that this is the case. Look in the `bsos` table, which contains the Binary Source Objects that each collection uses. 

As always, if you do discover something, don't be afraid to reach out to our security folk. I would recommend filing a bug on [bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Sync) since that has the setup for the bounty programs.

**Comment by martin-braun** [comment]
@jrconlin Thanks for explaining the encryption part, that makes things clearer to me and it is useful. I wasn't aware about the details of the sync service, I'm looking forward to switch back if I host things myself.

Also thank you for the links, very helpful.
