### ISSUE TITLE
Tune the actix-cors permissions for the newer library

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#930]
Per https://github.com/mozilla-services/syncstorage-rs/issues/928, we did a quick patch that relies on using nginx CORS wrappers for fine-tuned security. 

We should add better support around origin and other aspects of the CORS specification, due to increased actix-cors permission guidance. This may include adding additional options.

**Comment by pjenvey** [comment]
The outgoing headers don't seem terribly important since nginx writes a probably reasonable default set.

The strictness of the request processing is what needs to be looked into. We might just need to specify a value for `allowed_origin()`? And maybe ensure it's disabled for testing purposes (if necessary).

**Comment by jrconlin** [comment]
We definitely need to specify the `allowed_origin()`. Basically, we need to expose most of the CORS headers as configs since folks may need to alter them for themselves.
