### ISSUE TITLE
Compiling 0.8.3 under Debian Bullseye (alpha3)

### ISSUE THREAD

**Issue by vapaa** [mozilla-services/syncstorage-rs#956]
Hello all,

on a newly installed Debian Bullseye I get the following error message when compiling with syncstorage v0.8.3 (bin):

`error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/opt/syncstorage-rs/target/debug/deps/syncstorage-c42ae5e8b94bc60b.11i2awa9bq4x8pyq.rcgu.o" "/opt/syncstorage-rs/target/debug/deps/syncstorage-c42ae5e8b94bc60b.12cdwfk0drw3f9tg.rcgu.o" "/opt/syncstorage-rs/target/debug/deps/syncstorage-c42ae5e8b94bc60b.12va61dscmwbj2ij.rcgu.o" "/opt/syncstorage-rs/target/debug/deps/syncstorage"/opt/syncstorage-rs/target/debug/build/grpcio-sys-4a620cb63ad4c1e3/out/build/third_party/re2" "-L" "/opt/syncstorage-rs/target/debug/build/grpcio-sys-4a620cb63ad4c1e3/out/build/third_party/cares/cares/lib" "-L" "/opt/syncstorage-rs/target/debug/build/grpcio-sys-4a620cb63ad4c1e3/out" "-L" "/opt/syncstorage-rs/target/debug/build/libz-sys-a11f364e7c8f9018/out/build" "-L" "/opt/syncstorage-rs/target/debug/build/ring-d207e2c52139ca0a/out" "-L" "/usr/lib" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/opt/syncstorage-rs/target/debug/deps/libsyncstorage-9399655ddd26f97d.rlib" "/opt/syncstorage-rs/target/debug/deps/liburlencoding-46319f63abb14c10.rlib" 

----snip ---

bd645b20c6c7b56d.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-b9e1e523c0c29a77.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-dfbef8c525de0186.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-1ebf406bd4ea5769.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-5e0675f526ef5c6b.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-3375e4f89d420e7a.rlib" "-Wl,--end-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-f74b197469e67088.rlib" "-Wl,-Bdynamic" "-lpython3.9" "-lcurl" "-lssl" "-lcrypto" "-lstdc++" "-lmariadb" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-ldl" "-lutil"
  = note: /usr/bin/ld: cannot find -lpython3.9
          collect2: error: ld returned 1 exit status
          
error: aborting due to previous error

error: could not compile `syncstorage`.

To learn more, run the command again with --verbose.
make: *** [Makefile:29: run] Fehler 101`

I'm not getting anywhere at this point unfortunately.

Thanks and greetings

**Comment by jrconlin** [comment]
It would appear that from the message:
```
Bdynamic" "-lpython3.9" "-lcurl" "-lssl" "-lcrypto" "-lstdc++" "-lmariadb" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-ldl" "-lutil"
= note: /usr/bin/ld: cannot find -lpython3.9
collect2: error: ld returned 1 exit status
```
you don't have the latest version of python3.9 installed. As I understand, Bullseye is a development release of Debian, [the current stable version](https://www.debian.org/News/2020/20201205) being "buster". I don't believe that anyone on the team has tested for python3.9 yet. "buster" still uses python3.8. 

You can resolve this particular error by installing python 3.9 development library (I believe it's `libpython3.9-dev`) using your system package install tools. If you see similar errors, and because you're running on a not yet stable release, it can be useful to read over the returned errors to see if you might be missing system level packages. Some research may be required to identify newer versions. 

Good luck!

**Comment by vapaa** [comment]
perfect the server is running - thank you
